// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `Evictor.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef FREEZE_API_EXPORTS
#   define FREEZE_API_EXPORTS
#endif
#include <Freeze/Evictor.h>
#include <Ice/BasicStream.h>
#include <Ice/Object.h>
#include <IceUtil/Iterator.h>
#include <IceUtil/DisableWarnings.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

namespace
{

}

namespace
{

const char* __Freeze__NoSuchElementException_name = "Freeze::NoSuchElementException";

}

Freeze::NoSuchElementException::NoSuchElementException(const char* __file, int __line) :
    ::Ice::LocalException(__file, __line)
{
}

Freeze::NoSuchElementException::~NoSuchElementException() throw()
{
}

::std::string
Freeze::NoSuchElementException::ice_name() const
{
    return __Freeze__NoSuchElementException_name;
}

Freeze::NoSuchElementException*
Freeze::NoSuchElementException::ice_clone() const
{
    return new NoSuchElementException(*this);
}

void
Freeze::NoSuchElementException::ice_throw() const
{
    throw *this;
}

namespace
{

const char* __Freeze__EvictorDeactivatedException_name = "Freeze::EvictorDeactivatedException";

}

Freeze::EvictorDeactivatedException::EvictorDeactivatedException(const char* __file, int __line) :
    ::Ice::LocalException(__file, __line)
{
}

Freeze::EvictorDeactivatedException::~EvictorDeactivatedException() throw()
{
}

::std::string
Freeze::EvictorDeactivatedException::ice_name() const
{
    return __Freeze__EvictorDeactivatedException_name;
}

Freeze::EvictorDeactivatedException*
Freeze::EvictorDeactivatedException::ice_clone() const
{
    return new EvictorDeactivatedException(*this);
}

void
Freeze::EvictorDeactivatedException::ice_throw() const
{
    throw *this;
}

namespace Ice
{
}

ICE_DECLSPEC_EXPORT ::Ice::LocalObject* Freeze::upCast(::Freeze::ServantInitializer* p) { return p; }

ICE_DECLSPEC_EXPORT ::Ice::LocalObject* Freeze::upCast(::Freeze::EvictorIterator* p) { return p; }

ICE_DECLSPEC_EXPORT ::Ice::LocalObject* Freeze::upCast(::Freeze::Evictor* p) { return p; }
