// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `PingObject.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef FREEZE_API_EXPORTS
#   define FREEZE_API_EXPORTS
#endif
#include <Freeze/PingObject.h>
#include <Ice/LocalException.h>
#include <Ice/ObjectFactory.h>
#include <Ice/BasicStream.h>
#include <Ice/Object.h>
#include <IceUtil/Iterator.h>
#include <IceUtil/DisableWarnings.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

namespace
{

}
#ifdef __SUNPRO_CC
class ICE_DECLSPEC_EXPORT IceProxy::Freeze::PingObject;
#endif
ICE_DECLSPEC_EXPORT ::IceProxy::Ice::Object* ::IceProxy::Freeze::upCast(::IceProxy::Freeze::PingObject* p) { return p; }

void
::IceProxy::Freeze::__read(::IceInternal::BasicStream* __is, ::IceInternal::ProxyHandle< ::IceProxy::Freeze::PingObject>& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::Freeze::PingObject;
        v->__copyFrom(proxy);
    }
}

const ::std::string&
IceProxy::Freeze::PingObject::ice_staticId()
{
    return ::Freeze::PingObject::ice_staticId();
}

::IceInternal::Handle< ::IceDelegateM::Ice::Object>
IceProxy::Freeze::PingObject::__createDelegateM()
{
    return ::IceInternal::Handle< ::IceDelegateM::Ice::Object>(new ::IceDelegateM::Freeze::PingObject);
}

::IceInternal::Handle< ::IceDelegateD::Ice::Object>
IceProxy::Freeze::PingObject::__createDelegateD()
{
    return ::IceInternal::Handle< ::IceDelegateD::Ice::Object>(new ::IceDelegateD::Freeze::PingObject);
}

::IceProxy::Ice::Object*
IceProxy::Freeze::PingObject::__newInstance() const
{
    return new PingObject;
}

ICE_DECLSPEC_EXPORT ::Ice::Object* Freeze::upCast(::Freeze::PingObject* p) { return p; }
::Ice::ObjectPtr
Freeze::PingObject::ice_clone() const
{
    ::Ice::Object* __p = new PingObject(*this);
    return __p;
}

namespace
{
const ::std::string __Freeze__PingObject_ids[2] =
{
    "::Freeze::PingObject",
    "::Ice::Object"
};

}

bool
Freeze::PingObject::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__Freeze__PingObject_ids, __Freeze__PingObject_ids + 2, _s);
}

::std::vector< ::std::string>
Freeze::PingObject::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__Freeze__PingObject_ids[0], &__Freeze__PingObject_ids[2]);
}

const ::std::string&
Freeze::PingObject::ice_id(const ::Ice::Current&) const
{
    return __Freeze__PingObject_ids[0];
}

const ::std::string&
Freeze::PingObject::ice_staticId()
{
    return __Freeze__PingObject_ids[0];
}

void
Freeze::PingObject::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice(ice_staticId(), -1, true);
    __os->endWriteSlice();
}

void
Freeze::PingObject::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->endReadSlice();
}

namespace
{

class __F__Freeze__PingObject : public ::Ice::ObjectFactory
{
public:
#ifndef NDEBUG
virtual ::Ice::ObjectPtr
    create(const ::std::string& type)
#else
virtual ::Ice::ObjectPtr
    create(const ::std::string&)
#endif
    {
        assert(type == ::Freeze::PingObject::ice_staticId());
        return new ::Freeze::PingObject;
    }

    virtual void
    destroy()
    {
    }
};
const ::Ice::ObjectFactoryPtr __F__Freeze__PingObject_Ptr = new __F__Freeze__PingObject;

class __F__Freeze__PingObject__Init
{
public:

    __F__Freeze__PingObject__Init()
    {
        ::IceInternal::factoryTable->addObjectFactory(::Freeze::PingObject::ice_staticId(), __F__Freeze__PingObject_Ptr);
    }

    ~__F__Freeze__PingObject__Init()
    {
        ::IceInternal::factoryTable->removeObjectFactory(::Freeze::PingObject::ice_staticId());
    }
};

const __F__Freeze__PingObject__Init __F__Freeze__PingObject__i;

}

const ::Ice::ObjectFactoryPtr&
Freeze::PingObject::ice_factory()
{
    return __F__Freeze__PingObject_Ptr;
}

void ICE_DECLSPEC_EXPORT 
Freeze::__patch(PingObjectPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::Freeze::PingObjectPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::Freeze::PingObject::ice_staticId(), v);
    }
}
