// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `SubscriberMap.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


// Freeze types in this file:
// name="IceStorm::SubscriberMap", key="IceStorm::SubscriberRecordKey", value="IceStorm::SubscriberRecord"

#ifndef __SubscriberMap_h__
#define __SubscriberMap_h__

#include <Freeze/Map.h>
#include <IceStorm/SubscriberRecord.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

namespace IceStorm
{

class SubscriberMapKeyCodec
{
public:

    static void write(const ::IceStorm::SubscriberRecordKey&, Freeze::Key&, const ::Ice::CommunicatorPtr&, const Ice::EncodingVersion&);
    static void read(::IceStorm::SubscriberRecordKey&, const Freeze::Key&, const ::Ice::CommunicatorPtr&, const Ice::EncodingVersion&);
    static const std::string& typeId();
};

class SubscriberMapValueCodec
{
public:

    static void write(const ::IceStorm::SubscriberRecord&, Freeze::Value&, const ::Ice::CommunicatorPtr&, const Ice::EncodingVersion&);
    static void read(::IceStorm::SubscriberRecord&, const Freeze::Value&, const ::Ice::CommunicatorPtr&, const Ice::EncodingVersion&);
    static const std::string& typeId();
};

typedef Freeze::Map< ::IceStorm::SubscriberRecordKey, ::IceStorm::SubscriberRecord, SubscriberMapKeyCodec, SubscriberMapValueCodec, std::less< ::IceStorm::SubscriberRecordKey> > SubscriberMap;

}

#endif
