// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `Endpoint.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef ICE_API_EXPORTS
#   define ICE_API_EXPORTS
#endif
#include <Ice/Endpoint.h>
#include <Ice/BasicStream.h>
#include <Ice/Object.h>
#include <IceUtil/Iterator.h>
#include <IceUtil/DisableWarnings.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

namespace
{

}

ICE_DECLSPEC_EXPORT ::Ice::LocalObject* Ice::upCast(::Ice::EndpointInfo* p) { return p; }

ICE_DECLSPEC_EXPORT ::Ice::LocalObject* Ice::upCast(::Ice::Endpoint* p) { return p; }

ICE_DECLSPEC_EXPORT ::Ice::LocalObject* Ice::upCast(::Ice::IPEndpointInfo* p) { return p; }

ICE_DECLSPEC_EXPORT ::Ice::LocalObject* Ice::upCast(::Ice::TCPEndpointInfo* p) { return p; }

ICE_DECLSPEC_EXPORT ::Ice::LocalObject* Ice::upCast(::Ice::UDPEndpointInfo* p) { return p; }

ICE_DECLSPEC_EXPORT ::Ice::LocalObject* Ice::upCast(::Ice::OpaqueEndpointInfo* p) { return p; }
