// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `Instrumentation.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <Glacier2/Instrumentation.h>
#include <Ice/BasicStream.h>
#include <Ice/Object.h>
#include <IceUtil/Iterator.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

namespace
{

namespace
{

}

}

::Ice::LocalObject* Glacier2::Instrumentation::upCast(::Glacier2::Instrumentation::SessionObserver* p) { return p; }

::Ice::LocalObject* Glacier2::Instrumentation::upCast(::Glacier2::Instrumentation::ObserverUpdater* p) { return p; }

::Ice::LocalObject* Glacier2::Instrumentation::upCast(::Glacier2::Instrumentation::RouterObserver* p) { return p; }
